### ISSUE TITLE
Ethernet interface

### ISSUE THREAD

**Issue by hyzami** [rmoesbergen/openwrt#6]
Hello 
I have connected to my Turris other via ethernet old router that I use as AP. Is there any chance to add other interfaces to scan devices also connected over ethernet? 
Forward thanks for any information.

Best regards
Michael

**Comment by rmoesbergen** [comment]
Hi @hyzami ,

The presence detector works based on hostapd ubus events. For ethernet connected devices, there's no such event in ubus, since ethernet clients don't really 'connect/disconnect' to the router, but they just happen to be in the same ethernet network. However, there's a solution in home assistant for this type of device: the device_tracker 'ping' platform:
```
device_tracker:
  - platform: ping
    consider_home: 60
    count: 3
    hosts:
      mydevice: 192.168.10.55
```
The IP can also be a hostname. Make sure that the device accepts/responds to ICMP echo requests.
See also: https://www.home-assistant.io/integrations/ping/#presence-detection
